const decks = [
	"Japanese Core Vocab", [
		["arigatou", "Thank you"],
		["gomennasai", "Sorry"],
		["daijoubu", "Are you ok?"],
		["genkidesuka?", "How are you?"],
		["tsukareta", "I am tired"],
		["nemui", "I am sleepy"],
		["atsui", "It's hot"],
		["samui", "It's cold"],
		["hontou?", "Really?"],
		["chottodake", "Just a little bit"],
		["matte", "Wait"],
		["nani", "What is it?"],
		["watashi", "I"],
		["doushitano?", "What is wrong?"],
		["douomou?", "What do you think?"],
		["naruhodo", "I see"],
		["sugoi", "Amazing"],
		["imananji?", "What time is it now?"],
		["imadoko", "Where are we now?"],
		["nanitabetai?", "What do you want to eat?"],
		["naninomitai?", "What do you want to drink?"],
		["dare?", "Who?"],
		["joudan", "Just kidding"],
		["matane", "Wait"],
		["bikkurishita", "I was surprised"],
		["omoshiroi", "It's funny/interesting"],
		["omoshirokunai", "It's not funny/interesting"],
		["onakasuita", "I am hungry"],
		["onakaippai", "I am full"],
		["atamaitai", "My head hurts / I have a headache"],
		["kawaii", "Cute"],
		["kawaikunai", "Not cute"],
		["atamaii", "Smart"],
		["nansai?", "How old are you?"],
		["dokoshusshin?", "Where are you from?"],
		["dekinai", "I can't do it"],
		["benkyoushitai", "I want to study"],
		["benkyoushitakunai", "I don't want to study"],
		["hisashiburi", "Long time no see"],
		["kinchousuru", "I am nervous"],
		["ganbatte!", "Good luck!"],
		["suki", "I like it"],
		["sukijanai", "I don't like it"],
		["isogashii", "I am busy"],
		["tanoshimi", "I look forward to it"],
		["wakariyasui", "Easy to understand"],
		["wakarinikui", "Hard to understand"],
		["omedetou!", "Congratulations!"],
	]
]

document.getElementById("decklist").innerHTML = decks[0]