const decks = [
	"Japanese Core Vocab", [
		["arigatou", "Thank you"],
		["gomennasai", "Sorry"],
		["daijoubu", "Are you ok?"],
		["genkidesuka?", "How are you?"],
		["nemui", "I am sleepy"],
		["atsui", "It's hot"],
		["samui", "It's cold"],
		["hontou?", "Really?"],
		["matte", "Wait"],
		["nani?", "What is it?"],
		["watashi", "I"],
		["naruhodo", "I see"],
		["sugoi", "Amazing"],
		["imananji?", "What time is it now?"],
		["imadoko", "Where are we now?"],
		["dare?", "Who?"],
		["joudan", "Just kidding"],
		["matane", "Wait"],
		["bikkurishita", "I was surprised"],
		["onakasuita", "I am hungry"],
		["onakaippai", "I am full"],
		["atamaitai", "My head hurts / I have a headache"],
		["kawaii", "Cute"],
		["kawaikunai", "Not cute"],
		["atamaii", "Smart"],
		["nansai?", "How old are you?"],
		["dokoshusshin?", "Where are you from?"],
		["hisashiburi", "Long time no see"],
		["ganbatte!", "Good luck!"],
		["suki", "I like it"],
		["sukijanai", "I don't like it"],
		["omedetou!", "Congratulations!"],
	]
]